const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const { getDashboard } = require('../dashboard-data');
const { checkPinAccess } = require('./auth');

function naira(n) {
  return 'N' + Number(n || 0).toLocaleString('en-NG');
}

router.get('/api/report/:phone', async (req, res) => {
  try {
    const phone = req.params.phone;
    const providedPin = req.headers['x-buyna-pin'];
    const allowed = await checkPinAccess(phone, providedPin);
    if (!allowed) return res.status(401).json({ error: 'PIN required' });

    const d = await getDashboard(phone);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="buyna-report-${phone}.pdf"`);

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    doc.font('Helvetica-Bold').fontSize(22).text('BUYNA', { align: 'left' });
    doc.font('Helvetica').fontSize(10).fillColor('#666').text('Business report', { align: 'left' });
    doc.moveDown(0.3);
    doc.fontSize(9).text(`Trading as: ${phone}`);
    doc.text(`Generated: ${new Date().toLocaleString('en-NG')}`);
    doc.fillColor('#000');
    doc.moveDown(1);

    function section(title) {
      doc.moveDown(0.5);
      doc.font('Helvetica-Bold').fontSize(13).text(title);
      doc.moveTo(doc.x, doc.y + 2).lineTo(545, doc.y + 2).strokeColor('#ccc').stroke();
      doc.moveDown(0.4);
      doc.font('Helvetica').fontSize(10);
    }

    function row(label, value) {
      const y = doc.y;
      doc.text(label, 50, y);
      doc.text(value, 400, y, { width: 145, align: 'right' });
      doc.moveDown(0.3);
    }

    section('Today');
    row('Sales rung up', String(d.today.count));
    row('Total', naira(d.today.total));
    row('Profit', naira(d.today.profit));
    row('Expenses', naira(d.today.expenses));

    section('Last 7 days');
    row('Total', naira(d.week.total));
    row('Profit', naira(d.week.profit));
    row('Expenses', naira(d.week.expenses));

    if (d.capitalStatus) {
      section('Capital status');
      row('Capital', naira(d.capitalStatus.capital));
      row('Spent so far', naira(d.capitalStatus.spent));
      row('Remaining', naira(d.capitalStatus.remaining));
    }

    section('Stock on hand');
    if (!d.stock.length) {
      doc.fillColor('#999').text('No stock recorded.'); doc.fillColor('#000');
    } else {
      d.stock.forEach(s => row(s.item + (s.isLow ? ' (LOW)' : ''), String(s.quantity)));
    }

    section('Customers who owe you');
    if (!d.debts.length) {
      doc.fillColor('#999').text('Nobody owes you right now.'); doc.fillColor('#000');
    } else {
      d.debts.forEach(deb => row(deb.customerName, naira(deb.amount)));
    }

    section('Kolo savings');
    if (!d.kolo.length) {
      doc.fillColor('#999').text('No Kolo savings yet.'); doc.fillColor('#000');
    } else {
      d.kolo.forEach(k => row(k.goalName, naira(k.savedAmount) + (k.targetAmount > 0 ? ' / ' + naira(k.targetAmount) : '')));
    }

    if (d.recipes.length) {
      section('Recipe costs');
      d.recipes.forEach(r => row(r.name, naira(r.costPerItem) + ' / item'));
    }

    section('Recent sales');
    if (!d.recentSales.length) {
      doc.fillColor('#999').text('No sales recorded yet.'); doc.fillColor('#000');
    } else {
      d.recentSales.slice(0, 15).forEach(s => row(s.item + (s.recordedBy === 'apprentice' ? ' (apprentice)' : ''), naira(s.amount)));
    }

    section('Recent expenses');
    if (!d.recentExpenses.length) {
      doc.fillColor('#999').text('No expenses recorded yet.'); doc.fillColor('#000');
    } else {
      d.recentExpenses.forEach(e => row(e.category, naira(e.amount)));
    }

    doc.moveDown(1);
    doc.fontSize(8).fillColor('#999').text('Generated by BUYNA — your business, for Pidgin.', { align: 'center' });

    doc.end();
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Could not generate report' });
  }
});

module.exports = router;
